### ISSUE TITLE
Validate if user's first name is alphabetic or not

### ISSUE THREAD

**Issue by rahuldahal** [askbuddie/buddies-tube#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TheCodinggDude** [comment]
I would like to work on this issue.

**Comment by rahuldahal** [comment]
Sure!
But before that, let's have a short discussion on our [Discord Server](https://discord.gg/askbuddie)

**Comment by TheCodinggDude** [comment]
This discord invite link is invalid.

**Comment by rahuldahal** [comment]
I'm sorry!
[Here](https://discord.gg/uwvXuSqn) is the updated link that will be valid till October 7th.
