### ISSUE TITLE
Validate if user's last name is alphabetic or not

### ISSUE THREAD

**Issue by rahuldahal** [askbuddie/buddies-tube#16]
**Describe the solution you'd like**
Currently, the [User Schema](https://github.com/askbuddie/buddies-tube/blob/develop/backend/src/models/User/index.js) has no validation for [lastName](https://github.com/askbuddie/buddies-tube/blob/00693d2a1aa3ac83d1bf0f02084e2d27b796892c/backend/src/models/User/structure.js#L6).

Use [validator.js](https://www.npmjs.com/package/validator)'s(already installed) `isAlpha(string)` function to "test" for alphabetic string.

**Additional context**
[Here](https://github.com/askbuddie/buddies-tube/blob/00693d2a1aa3ac83d1bf0f02084e2d27b796892c/backend/src/models/User/index.js#L27) is an example of how/where to use the validation.

**Note**
Make sure the validation message reads, "The last name should only contain alphabets"

**Comment by rajdama** [comment]
I can do it.

**Comment by rahuldahal** [comment]
Sure!
But before that, let's have a short discussion on our [Discord Server](https://discord.gg/askbuddie)

**Comment by rajdama** [comment]
Okay

**Comment by rajdama** [comment]
The link is expired can you share it again ?

**Comment by rahuldahal** [comment]
I'm sorry!
[Here](https://discord.gg/uwvXuSqn) is the updated link that will be valid till October 7th.

**Comment by rajdama** [comment]
Yea I joined : )
