### ISSUE TITLE
Respond with a JWT token after successful login

### ISSUE THREAD

**Issue by rahuldahal** [askbuddie/buddies-tube#24]
**Describe the solution you'd like**
Currently, the [user controller](https://github.com/askbuddie/buddies-tube/blob/07f19dfef69b5a65f98d593e7172c5d780f4b89f/src/controllers/users.js#L65) responds with a sample message like, "Trying to log in for [email]".
Use [jsonwebtoken](https://github.com/auth0/node-jsonwebtoken#readme) npm package(already installed) to create a JWT token with user's basic information.

Send that JWT as the response body

**Comment by roman-rezinkin** [comment]
Hi, I would like to contribute to this. Could you add the hacktoberfest tag?

**Comment by roman-rezinkin** [comment]
I have made a PR with the change, please review it https://github.com/askbuddie/buddies-tube/pull/25
